/**
 * `@alchemy.run/frontend-frameworks/vinext/aws` — vinext on AWS Lambda.
 *
 * vinext's AWS story is a plain-Node `vinext build` (no Cloudflare Vite
 * plugin) plus a finishing pass that wraps the App Router RSC entry
 * (`dist/server/index.js`) as a streaming Lambda handler via
 * `@alchemy.run/frontend-frameworks/aws-lambda`. Static assets in
 * `dist/client` are uploaded to S3 by `AWS.Website.Vinext`.
 *
 * - **`build`** runs `vinext build` in a disposable child, then writes
 *   `dist/server/serve-aws-lambda.mjs` exporting `handler`.
 * - **`dev`** runs the real `vinext dev` CLI (plain Node), scoped.
 *
 * This is **not** OpenNext and **not** `Cloudflare.Website.Vinext`.
 * App Router only — Pages Router has no single fetch handler to wrap.
 *
 * Composites should load this module as both the framework specifier and
 * the deploy target (same shape as `nextjs/aws`).
 */
import * as FrameworkCore from "../core/index.ts";
import * as NodeChildProcessSpawner from "@effect/platform-node/NodeChildProcessSpawner";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import * as Path from "effect/Path";
import type * as Scope from "effect/Scope";
import { fileURLToPath } from "node:url";
import { runBuildChild } from "../core/BuildChild.ts";
import {
  DeployTargetError,
  makeDeployTarget,
  type DeployTarget,
} from "../core/index.ts";
import {
  awaitVinextDevReady,
  collectVinextDist,
  failFramework,
  pickEphemeralPort,
  pinServeModule,
  resolveVinextCli,
  runVinextBuild,
  spawnVinextDev,
  VINEXT_RSC_ENTRY,
} from "./cli.ts";

const failTarget = (message: string, cause?: unknown) =>
  new DeployTargetError({ platform: "aws", message, cause });

/** Options for the vinext AWS framework module / deploy target. */
export interface VinextAwsOptions {
  readonly root?: string | undefined;
  /**
   * The deploy target module specifier the caller resolved this module as.
   * This module IS the AWS target — accepted and ignored.
   */
  readonly target?: string | undefined;
  /**
   * Whether the emitted Lambda handler streams its response
   * (`awslambda.streamifyResponse`, requires a Function URL with
   * `invokeMode: RESPONSE_STREAM`).
   * @default true
   */
  readonly streaming?: boolean | undefined;
}

export interface VinextAwsTargetConfig {
  readonly root?: string | undefined;
  readonly streaming?: boolean | undefined;
}

export interface VinextAwsTarget extends DeployTarget<VinextAwsTargetConfig> {}

/** The Lambda entry the finishing pass writes into `dist/server`. */
export const SERVE_ENTRY_NAME = "server/serve-aws-lambda.mjs";

/** The on-disk copy of this package's `aws-lambda` web adapter runtime. */
export const LAMBDA_ADAPTER_FILE_NAME = "vinext-aws-lambda.mjs";

/**
 * The generated Lambda entry: imports vinext's App Router fetch handler
 * and exports it wrapped for the Lambda Node.js runtime.
 */
export const makeLambdaEntrySource = (streaming: boolean): string => {
  const wrap = streaming ? "toLambdaHandler" : "toBufferedLambdaHandler";
  return `// Generated by @alchemy.run/frontend-frameworks/vinext/aws — do not edit.
import rsc from "./index.js";
import { ${wrap} } from "./${LAMBDA_ADAPTER_FILE_NAME}";

const fetchHandler = (request) => {
  const ctx = {
    hostRuntime: "node",
    waitUntil(promise) {
      Promise.resolve(promise).catch(() => {});
    },
    passThroughOnException() {},
  };
  if (typeof rsc === "function") return rsc(request, ctx);
  return rsc.fetch(request, process.env, ctx);
};

export const handler = ${wrap}(fetchHandler);
`;
};

const resolveLambdaAdapterPath = Effect.try({
  try: () =>
    fileURLToPath(
      import.meta.resolve("@alchemy.run/frontend-frameworks/aws-lambda"),
    ),
  catch: (cause) =>
    failFramework(
      'Failed to resolve "@alchemy.run/frontend-frameworks/aws-lambda" — is the package built (its exports map serves dist/)?',
    )(cause),
});

export interface VinextAwsBuildChildConfig {
  readonly rootDir: string;
  readonly config: VinextAwsTargetConfig;
}

export const buildInChild = (config: VinextAwsBuildChildConfig) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const root = config.rootDir;
    const cli = yield* resolveVinextCli(root);
    const spawnerLayer = NodeChildProcessSpawner.layer.pipe(
      Layer.provide(
        Layer.merge(
          Layer.succeed(FileSystem.FileSystem)(fs),
          Layer.succeed(Path.Path)(path),
        ),
      ),
    );
    yield* runVinextBuild({ root, cli, cache: "s3" }).pipe(
      Effect.provide(spawnerLayer),
    );
    const dist = yield* collectVinextDist(root);
    if (!dist.hasRsc) {
      return yield* Effect.fail(
        failFramework(
          `The vinext AWS target requires an App Router build (${VINEXT_RSC_ENTRY}). Pages Router is supported on Node containers, not Lambda.`,
        )(undefined),
      );
    }
    const adapterPath = yield* resolveLambdaAdapterPath;
    const adapterSource = yield* fs
      .readFileString(adapterPath)
      .pipe(
        Effect.mapError(
          failFramework("Failed to read the aws-lambda adapter module"),
        ),
      );
    yield* fs
      .writeFileString(
        path.join(dist.serverDir, LAMBDA_ADAPTER_FILE_NAME),
        adapterSource.replace(/^\/\/# sourceMappingURL=.*$/m, ""),
      )
      .pipe(
        Effect.mapError(
          failFramework(
            "Failed to write the aws-lambda adapter into dist/server",
          ),
        ),
      );
    return yield* pinServeModule(
      dist,
      SERVE_ENTRY_NAME,
      makeLambdaEntrySource(config.config.streaming !== false),
    );
  });

const makeAwsChildTarget = (
  config: VinextAwsTargetConfig = {},
): VinextAwsTarget =>
  makeDeployTarget({
    platform: "aws",
    config,
    bundle: {
      conditions: ["node", "import", "module"],
      external: ["@aws-sdk/"],
    },
  });

/**
 * Create the AWS Lambda {@link VinextAwsTarget}. See the module doc.
 */
export const makeAwsTarget = (
  config: VinextAwsTargetConfig = {},
): VinextAwsTarget => ({
  ...makeAwsChildTarget(config),
  build: (context) =>
    runBuildChild({
      module: import.meta.url,
      rootDir: context.root,
      env: context.env,
      framework: "vinext",
      config: {
        rootDir: context.root,
        config,
      } satisfies VinextAwsBuildChildConfig,
    }).pipe(Effect.mapError((error) => failTarget(error.message, error.cause))),
});

export const target = makeAwsTarget;

export default makeAwsTarget;

export interface VinextAwsService {
  readonly build: (
    options?: FrameworkCore.FrameworkBuildOptions,
  ) => Effect.Effect<
    {
      readonly distDirectory: string;
      readonly clientDirectory: string | undefined;
      readonly serverModules: Array<{ readonly name: string }>;
    },
    FrameworkCore.FrameworkError
  >;
  readonly dev: (
    options?: FrameworkCore.FrameworkDevOptions,
  ) => Effect.Effect<
    FrameworkCore.FrameworkDevServer,
    FrameworkCore.FrameworkError,
    Scope.Scope
  >;
}

/**
 * Build the vinext-on-AWS framework service. See the module doc for the
 * `build`/`dev` semantics.
 */
export const make: (
  options?: VinextAwsOptions,
) => Effect.Effect<VinextAwsService, never, FileSystem.FileSystem | Path.Path> =
  Effect.fnUntraced(function* (options?: VinextAwsOptions) {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const resolveRoot = (override: string | undefined) =>
      Effect.sync(() =>
        path.resolve(override ?? options?.root ?? process.cwd()),
      );

    const build: VinextAwsService["build"] = Effect.fn(function* (
      buildOptions?: FrameworkCore.FrameworkBuildOptions,
    ) {
      const root = yield* resolveRoot(buildOptions?.root);
      const awsTarget = makeAwsTarget({
        root,
        streaming: options?.streaming,
      });
      const output = yield* awsTarget.build!({
        root,
        framework: "vinext",
      }).pipe(
        Effect.provideService(FileSystem.FileSystem, fs),
        Effect.provideService(Path.Path, path),
        Effect.mapError((error) => failFramework(error.message)(error.cause)),
      );
      return {
        distDirectory: output.distDirectory ?? path.join(root, "dist"),
        clientDirectory: output.clientDirectory,
        serverModules: (output.serverModules ?? []).map((module_) => ({
          name: module_.name,
        })),
      };
    });

    const dev: VinextAwsService["dev"] = Effect.fn(function* (
      devOptions?: FrameworkCore.FrameworkDevOptions,
    ) {
      const root = yield* resolveRoot(devOptions?.root);
      const port = devOptions?.port ?? (yield* pickEphemeralPort);
      const cli = yield* resolveVinextCli(root);
      const host = devOptions?.host ?? "127.0.0.1";
      const child = yield* spawnVinextDev({ root, cli, port, host });
      const url = `http://${host}:${port}`;
      yield* awaitVinextDevReady({ url, child });
      return { url };
    });

    return { build, dev };
  });
